### PR TITLE
where

### PR DESCRIPTION
**Pull request by chiron852**
where

### CODE REVIEW

**Comment by Mxtyx** [comment]
L bozo keep coming like a dog i will give you my dick as a treat turkish dumbass and thank you because you forked my readme lmao ez fork I feel famous

**Comment by chiron852** [comment]
> L bozo keep coming like a dog i will give you my dick as a treat turkish dumbass and thank you because you forked my readme lmao ez fork I feel famous

where

**Comment by chiron852** [comment]
ok now tell me all things you have i mean all infos about me

**Comment by chiron852** [comment]
bc i dont want you to sell them to people like boosters it would be bad as hell

**Pull request closed without merging**
